replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90
image:
  repository: vaadin/control-center-app
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  automount: true
  clusterAdmin: false
service:
  type: LoadBalancer
  port: 8000
  targetPort: 8080
resources: {}
